name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'gateway-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'gateway-service/**'
  workflow_dispatch:

jobs:
  api-gateway-build:
    if: "contains(github.event.head_commit.message, 'gateway-service')"  # Run if commit message contains 'gateway-service'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python for gateway-service
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies for gateway-service
        working-directory: gateway-service  # Ensure we are in the correct directory
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        working-directory: gateway-service  # Specify working directory for Dockerfile
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/autochoice/gateway-svc:latest

      # Tagging the Docker image
      - name: Tag Docker image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/autochoice/gateway-svc:latest ${{ secrets.DOCKER_USERNAME }}/autochoice:latest

      # Pushing the tagged Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/autochoice:latest
