# api-gateway Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
  labels:
    app: gateway-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
        - name: gateway-svc
          image: gateway-svc:latest # Replace with your actual image
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-svc"
#            - name: VEHICLE_SERVICE_URL
#              value: "http://vehicle-svc"
#            - name: BOOKING_SERVICE_URL
#              value: "http://booking-svc"
#            - name: POST_SALE_SERVICE_URL
#              value: "http://post-sale-svc"
#            - name: ROADSIDE_ASSISTANCE_URL
#              value: "http://roadside-assistance-svc"
#            - name: CUSTOMER_FEEDBACK_URL
#              value: "http://customer-feedback-svc"
            - name: CUSTOMER_SERVICE_URL
              value: "http://customer-svc"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  type: NodePort  # Changed to NodePort for local access
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30081  # Specify a port between 30000-32767
  selector:
    app: gateway-svc

# customer-service Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-svc
  template:
    metadata:
      labels:
        app: customer-svc
    spec:
      containers:
        - name: customer-svc
          image: customer-svc:latest  # Using the locally built image
          imagePullPolicy: Never
          ports:
            - containerPort: 8007
---
apiVersion: v1
kind: Service
metadata:
  name: customer-svc
spec:
  selector:
    app: customer-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8007
  type: ClusterIP  # Internal access only, suitable for local deployment
