name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'api-gateway/**'
  pull_request:
    branches:
      - main
    paths:
      - 'api-gateway/**'
  workflow_dispatch:

jobs:
  api-gateway-build:
    if: "contains(github.event.head_commit.message, 'api-gateway')"  # Run if commit message contains 'api-gateway'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python for api-gateway
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies for api-gateway
        working-directory: api-gateway  # Run for the api-gateway module
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image for api-gateway
        working-directory: api-gateway
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/autochoice/autochoice:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/autochoice:latest

  # another-module-build:
  #   if: "contains(github.event.head_commit.message, 'another-module')"  # Run if commit message contains 'another-module'
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Python for another-module
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.10'

  #     - name: Install dependencies for another-module
  #       working-directory: another-module  # Run for another module
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Build and Push Docker image for another-module
  #       working-directory: another-module
  #       run: |
  #         docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/autochoice/another-module-svc:latest
  #         docker push ${{ secrets.DOCKER_USERNAME }}/autochoice/another-module-svc:latest


# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build Docker image
#         run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/autochoice/gateway-svc:latest

#       - name: Push Docker image
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/autochoice/gateway-svc:latest
