openapi: 3.0.0
info:
  title: Customer Service API
  description: API for managing customer data in AutoHub platform.
  version: 1.0.0
servers:
  - url: http://localhost:8007

paths:
  /customers:
    get:
      summary: Get all customers
      description: Retrieve a list of all customers
      responses:
        '200':
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '500':
          description: Internal server error
    post:
      summary: Create a new customer
      description: Add a new customer to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Invalid input
  /customers/{customerId}:
    get:
      summary: Get customer details
      description: Retrieve details of a specific customer by ID
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found
    put:
      summary: Update customer information
      description: Update the details of an existing customer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Invalid input
        '404':
          description: Customer not found
    delete:
      summary: Delete a customer
      description: Remove a customer from the system by ID
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Customer deleted successfully
        '404':
          description: Customer not found

components:
  schemas:
    Customer:
      type: object
      required:
        - firstName
        - lastName
        - email
        - userId
      properties:
        userId:
          type: string
          description: Unique identifier for the user
        firstName:
          type: string
          description: First name of the customer
        lastName:
          type: string
          description: Last name of the customer
        email:
          type: string
          description: Email address of the customer
        phoneNumber:
          type: string
          description: Phone number of the customer
        address:
          type: string
          description: Address of the customer
